### ISSUE TITLE
Distance Matrix

### ISSUE THREAD

**Issue by datalorax** [OR-K-Entry/ec-providers#3]
Just a note that I have been able to successful figure out how to use google's Distance Matrix API (see [here](https://developers.google.com/maps/documentation/distance-matrix/start)) to calculate travel time between two places based on longitude/latitude. I'm going to check in with our business manager to see if we can absorb the cost of doing this but I don't think it should be a big deal, and then we'd have really good info on how far these providers actually are from the K-12 schools!

See attached screenshot for the type of data we get back (it's JSON, but we can parse that, of course).
![Screen Shot 2020-05-18 at 8 14 18 PM](https://user-images.githubusercontent.com/10944136/82280860-be6f1c00-9944-11ea-89e3-07895a8dc4cb.png)

Will close this issue once I've been able to pull all distances. Not sure if it's feasible to pull all distances between every school and every provider. Maybe we just do it for providers within the same county as the school?

**Comment by jrosen48** [comment]
Excellent!

Hmmmmm. One issue with a county - a school could be very near to a provider but right on the other side of a county's border.

What if we did a coarse(r) analysis using Mahalanobis distance, and then only calculated travel distance for e.g. those less than 75 miles away?

Also, it's not like looking within counties (or maybe counties plus neighboring counties?) would give us biased results. Just thinking through this!

**Comment by datalorax** [comment]
Yes, I actually though that exact thing after suggesting that. Basing it on a "as the crow flies" range would be better than arbitrary county lines. I'll see if I can do something like that.

**Comment by datalorax** [comment]
Okay, I just pushed a script that creates two files, one for all providers within 100 miles of a given school, and the other for all pairwise combinations of schools and providers and the miles between them. I had to ignore the actual files because they were too large, but you can run the script and it should create them for you.

For now, I used the haversine distance, which is as the crow flies distance, but does take into account the curvature of the earth (it assumes it's perfectly round, so not perfect, but good enough). 

@jrosen48, if you have time, you could do some preliminary modeling with these haversine distances. I may play around with them a bit too.

**Comment by datalorax** [comment]
Also, I"m actually not sure it's feasible to use the google API. Even if we limit it to providers within a 50 mile as the crow flies distance, there's over 650K requests we'd have to make which, when allowing for some fudge room, would end up being ~$3K. I'm not sure it's worth that even if we can afford it. I have a request in to google to see if they'll work with me on cost some, but these may be the distances we just want to end up using.

**Comment by datalorax** [comment]
Sorry, last thing for now. Looks like there are alternatives that are potentially (considerably) cheaper: https://gis.stackexchange.com/questions/15199/looking-for-free-web-service-that-calculates-driving-distance-between-2-addresse

**Comment by jrosen48** [comment]
sounds good about preliminary analyses with these data (and good to learn about what a haversine distance is...) - will plan to create a new script for this.

am blown away by the _n_ of distances between providers and schools! that's wild. I agree that using these is likely sufficient. Lots of ways we could go to address this; one small one is to use the Google Maps (or a less-expensive option) for a sample of the providers-schools combinations, and check how different they are (and in what direction), to gain a sense of how bias might enter the picture. just one idea among others.

**Comment by datalorax** [comment]
Yeah I actually hadn't heard of the haversine distance before either, but it's pretty neat. I like the idea of using the driving directions for a small random sample. My guess is we'd end up with very similar results but that would be a good robustness check.

**Comment by jrosen48** [comment]
Just added some initial thoughts (and comments - I think we will be in business with these or can at least start to calculate values like those you want to use in analyses when we have the quality ratings. These thoughts are in:

[`scripts/calc-exposure.R`](https://github.com/OR-K-Entry/ec-providers/blob/master/scripts/calc-exposure.R)

**Comment by jrosen48** [comment]
random thought - some scholars are arguing that this approach for calculating exposure is inferior to a newly-developed ('latent space') approach that uses a latent variable. Ran Xu (and Ken Frank) have been advocating this. Here is a nice paper from Ran: https://arxiv.org/pdf/1903.05999.pdf

Especially given that we're working with spatial data, this seems like it could be a natural fit. Ran does provide a tutorial in that paper. I will review it but welcome your input on this.

**Comment by datalorax** [comment]
Wonderful! I'm going to close this issue for now and we can open a new one to discuss specifics on modeling.
